const songs = [
  {
    title: "#KuSangatSuka",
    cover: "assets/covers/sukinanda.webp",
    audio: "assets/audio/lagu/kusangatsuka.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "1! 2! 3! 4! Yoroshiku!",
    cover: "assets/covers/yuhi.webp",
    audio: "assets/audio/lagu/1_2_3_4_yoroshiku.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "100 Meter ke Minimarket",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/100_meter_ke_minimarket.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "Medium",
  },
  {
    title: "109 - Marukyuu (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio: "assets/audio/lagu/109_marukyuu_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "16 Warna Crayon Mimpi",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/16_warna_crayon_mimpi.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Ada Aku!",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/ada_aku.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Adrenalin Masa Puber",
    cover: "assets/covers/believe.webp",
    audio: "assets/audio/lagu/adrenalin_masa_puber.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Adyth",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M10_adit.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "After Rain",
    cover: "assets/covers/Hightension.webp",
    audio: "assets/audio/lagu/after_rain.mp3",
    type: "Single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Air Mata Perasaan yang Tak Tersampaikan",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/air_mata_perasaan_yang_tak_tersampaikan.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Air Mata Surprise!",
    cover: "assets/covers/heavyrotation.webp",
    audio: "assets/audio/lagu/air_mata_surprise.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Aishiteraburu",
    cover: "assets/covers/indahnyasenyum.webp",
    audio: "assets/audio/lagu/aishiteraburu.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Ajak Aku Pergi Menuju ke Wimbledon",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/ajak_aku_pergi_menuju_ke_wimbledon.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Aku Akan Berjuang",
    cover: "assets/covers/ginghamcheck.webp",
    audio: "assets/audio/lagu/aku_akan_berjuang.mp3",
    type: "album",
    setlist: null,
    popularity: "",
  },
  {
    title: "Aku Sangat Suka",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/aku_sangat_suka.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Aku, Juliette dan Jet Coaster",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/aku_juliette_dan_jet_coaster.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Alasanku Maybe",
    cover: "assets/covers/kokoro.webp",
    audio: "assets/audio/lagu/alasanku_maybe.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Alibi Kecemburuan",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/alibi_kecemburuan.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Andai 'Ku Bukan Idola'Ku Bukan Idola",
    cover: "assets/covers/idolnangka.webp",
    audio: "assets/audio/lagu/andai_ku_bukan_idola.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Andai Ku Dapat Ungkapkan Cinta",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/andai_ku_dapat_ungkapkan_cinta.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Low",
  },
  {
    title: "Angin Kita",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/angin_kita.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Angin Musim Semi Pertama",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/angin_musim_semi_pertama.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Angin Sedang Berhembus",
    cover: "assets/covers/kaze.webp",
    audio: "assets/audio/lagu/angin_sedang_berhembus.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Antenna",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/antenna.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Apa yang Sang Gadis Perbuat di Musim Panas?",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/apa_yang_sang_gadis_perbuat_di_musim_panas.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Apakah Kau Melihat Mentari Senja?",
    cover: "assets/covers/yuhi.webp",
    audio: "assets/audio/lagu/apakah_kau_melihat_mentari_senja.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Apel yang Ada di Puncak",
    cover: "assets/covers/pareo.webp",
    audio: "assets/audio/lagu/apel_yang_ada_di_puncak.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Arah Sang Cinta dan Balasannya",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/arah_sang_cinta_dan_balasannya.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Aturan Anti Cinta",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/aturan_anti_cinta.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Ayo Mulai Dari Salam",
    cover: "assets/covers/ayomulaisalam.webp",
    audio: "assets/audio/lagu/ayo_mulai_dari_salam.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Ayo Penuh Skandal",
    cover: "assets/covers/k3_stage.webp",
    audio: "assets/audio/lagu/ayo_penuh_skandal.mp3",
    type: "setlist",
    setlist: "kiii",
    popularity: "Low",
  },
  {
    title: "Baby! Baby! Baby!",
    cover: "assets/covers/heavyrotation.webp",
    audio: "assets/audio/lagu/baby_baby_baby.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Baby! Baby! Baby! (Passionate)",
    cover: "assets/covers/kfc.webp",
    audio: "assets/audio/lagu/baby_baby_baby_passionate_prayer_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Back Hip Circle",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/back_hip_circle.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "High",
  },
  {
    title: "Baju Putih",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/baju_putih.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Balada Serangga",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/balada_serangga.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Low",
  },
  {
    title: "Ballerina dalam Sepi",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/ballerina_dalam_sepi.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Banzai Venus",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/banzai_venus.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Barcode Hati Ini",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/barcode_hati_ini.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Beach Sandal",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/beach_sandal.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Beginner",
    cover: "assets/covers/beginner.webp",
    audio: "assets/audio/lagu/beginner.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Beginner's Gamble's",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/beginners_gamble.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Bel Sekolah adalah Love Song",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/bel_sekolah_adalah_love_song.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Bel Terakhir Berbunyi",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M02_Bel_Terakhir_Berbunyi.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "High",
  },
  {
    title: "Belalang yang Membangkang",
    cover: "assets/covers/belalang.webp",
    audio: "assets/audio/lagu/belalang_yang_membangkang.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Beloklah ke Kanan",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/beloklah_ke_kanan.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Benang Sari, Putik, dan Kupu-Kupu Malam (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio:
      "assets/audio/lagu/benang_sari_putik_dan_kupukupu_malam_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Bentuk Sang Rembulan",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M11_Bentuk_sang-rembulan.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "High",
  },
  {
    title: "Berandalan di Surga",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/berandalan_di_surga.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Low",
  },
  {
    title: "Berikan Coklat dengan Bibir",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/berikan_coklat_dengan_bibir.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Berkedip 3 kali",
    cover: "assets/covers/kaze.webp",
    audio: "assets/audio/lagu/berkedip_3_kali.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Bersama kamu, Pelangi, dan Mentari",
    cover: "assets/covers/joy_kick_tears.webp",
    audio: "assets/audio/lagu/bersama_kamu_pelangi_dan_mentari.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Bersama-Sama Semuanya",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/bersamasama_semuanya.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "Bersepeda Berdua",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/bersepeda_berdua.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Betapa Indahnya Dunia Tempat Kita Terlahir",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/betapa_indahnya_dunia_tempat_kita_terlahir.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Better",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/better.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Bibir dari Plastik",
    cover: "assets/covers/bibirdrplastik.webp",
    audio: "assets/audio/lagu/bibir_dari_plastik.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Bibir yang Telah Dicuri",
    cover: "assets/covers/sukinanda.webp",
    audio: "assets/audio/lagu/bibir_yang_telah_dicuri.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "BINGO!",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/bingo.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Bird",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M04_Bird.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "High",
  },
  {
    title: "Birth",
    cover: "assets/covers/solong.webp",
    audio: "assets/audio/lagu/birth.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Blue Rose",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/blue_rose.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Boneka Teddy Bear",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/boneka_teddy_bear.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Boneka Yang Sedih",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M01_Boneka_yg_sedih.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Buah Masa Depan",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/buah_masa_depan.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Buah Mawar",
    cover: "assets/covers/pareo.webp",
    audio: "assets/audio/lagu/buah_mawar.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Bukan Alpukat",
    cover: "assets/covers/bukanalpukat.webp",
    audio: "assets/audio/lagu/bukan_alpukat.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Bukan Salah Air Mata",
    cover: "assets/covers/bukanalpukat.webp",
    audio: "assets/audio/lagu/bukan_salah_air_mata.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Bunga Matahari",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/bunga_matahari.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Bunga Sakuraku",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/bunga_sakuraku.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Bunga yang 'Kan Mekar Suatu Saat",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/bunga_yang_kan_mekar_suatu_saat.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Burung Unta si Pembohong",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/burung_unta_si_pembohong.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Cahaya Panjang",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/cahaya_panjang.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Candy",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M07_Candy.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Cara Ceroboh untuk Mencinta",
    cover: "assets/covers/darashinai.webp",
    audio: "assets/audio/lagu/cara_ceroboh_untuk_mencinta.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Cara Meminum Ramune",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/cara_meminum_ramune.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Cara Mendapatkan Pacar",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M03_Cara_mendapatkan_Pacar.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Cara Menggunakan Hidup",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/cara_menggunakan_hidup.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Cherry Tepi Pantai",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M04_Cherry_tepi_pantai.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Cinderella tak akan tertipu",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/cinderella_tak_akan_tertipu.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Cinta dalam Handshake",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/cinta_dalam_handshake.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Cinta di Garis Horizon",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/cinta_di_garis_horizon.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Cinta Higurashi",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/cinta_higurashi.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "cinta murni crescendo",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/cinta_murni_crescendo.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Cinta Pertama Butterfly",
    cover: "assets/covers/solong.webp",
    audio: "assets/audio/lagu/cinta_pertama_butterfly.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Cinta Pertama di Jam 7 lewat 12",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/cinta_pertama_di_jam_7_lewat_12.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Cinta Pertamaku, Selamat Siang",
    cover: "assets/covers/dewi.webp",
    audio:
      "assets/audio/setlist/Dewi_Theater/M05_Cinta_pertama_selamat-siang.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "Medium",
  },
  {
    title: "Cinta Remaja",
    cover: "assets/covers/jkt48acoustic.webp",
    audio: "assets/audio/lagu/cinta_remaja.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Cinta Tak Berbalas Finally",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/cinta_tak_berbalas_finally.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "City Lights",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/city_lights.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Ciuman Juga Kidal",
    cover: "assets/covers/kaze.webp",
    audio: "assets/audio/lagu/ciuman_juga_kidal.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Ciuman Kelulusan",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/ciuman_kelulusan.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Classmate",
    cover: "assets/covers/J_Believe.webp",
    audio: "assets/audio/lagu/classmate.mp3",
    type: "setlist",
    setlist: "teamJshow",
    popularity: "Medium",
  },
  {
    title: "Coolgirl",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M11_Cool-Girl.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "cowok durian",
    cover: "assets/covers/indahnyasenyum.webp",
    audio: "assets/audio/lagu/cowok_durian.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Cross",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/cross.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Dahulu",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/dahulu.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Dai Dai Dai",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/dai_dai_dai.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Dari Atas Melody",
    cover: "assets/covers/rh2016.webp",
    audio: "assets/audio/lagu/dari_atas_melody.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Dash Cinta pertama",
    cover: "assets/covers/flyteamt.webp",
    audio: "assets/audio/lagu/dash_cinta_pertama.mp3",
    type: "setlist",
    setlist: "flt",
    popularity: "Low",
  },
  {
    title: "Dear J",
    cover: "assets/covers/dearj.webp",
    audio: "assets/audio/lagu/dear_j.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "DEAR MY TEACHER",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M10_Dear-My_Teacher.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Deja Vu",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/deja_vu.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "Medium",
  },
  {
    title: "Demi Seseorang",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M12_Demi_seseorang.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "High",
  },
  {
    title: "Dengan Berbagai Alasan",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/dengan_berbagai_alasan.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Dewi Theater",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M04_Dewi-Theater.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "Medium",
  },
  {
    title: "Di antara Kekuatan dan Kelemahan",
    cover: "assets/covers/diantarakelemahan.webp",
    audio: "assets/audio/lagu/di_antara_kekuatan_dan_kelemahan.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Di Bawah Langit Berwarna Sakura",
    cover: "assets/covers/mahagita1.webp",
    audio: "assets/audio/lagu/di_bawah_langit_berwarna_sakura.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Di Sini Rhodes, Lompatlah di Sini",
    cover: "assets/covers/solong.webp",
    audio: "assets/audio/lagu/di_sini_rhodes_lompatlah_di_sini.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Di Tempat yang Jauh pun",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/di_tempat_yang_jauh_pun.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Di Tengah Hujan Badai Tiba-tiba",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/di_tengah_hujan_badai_tibatiba.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Dialog Dengan Kenari",
    cover: "assets/covers/kokoro.webp",
    audio: "assets/audio/lagu/dialog_dengan_kenari.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Dialog dengan Kenari (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio: "assets/audio/lagu/dialog_dengan_kenari_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Dibanding Kemarin Semakin Suka",
    cover: "assets/covers/pareo.webp",
    audio: "assets/audio/lagu/dibanding_kemarin_semakin_suka.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Dirimu Melody",
    cover: "assets/covers/melody.webp",
    audio: "assets/audio/lagu/dirimu_melody.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Disco di UKS",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/disco_di_uks.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Don't Disturb!",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/dont_disturb.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "Medium",
  },
  {
    title: "Don't Look Back",
    cover: "assets/covers/halLoween.webp",
    audio: "assets/audio/lagu/dont_look_back.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Double Standard",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/double_standard.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Doubt!",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/doubt.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Dream",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/dream.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Dreamin’ girls",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/dreamin_girls.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Dua Orang yang Terlarang",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/dua_orang_yang_terlarang.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "Medium",
  },
  {
    title: "Dukungan",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M16_Dukungan.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Ekor Malaikat",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/ekor_malaikat.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "End Roll",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/end_roll.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Escape",
    cover: "assets/covers/pareo.webp",
    audio: "assets/audio/lagu/escape.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Eureka Milik Kita",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/eureka_milik_kita.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Eureka Milik Kita (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio: "assets/audio/lagu/eureka_milik_kita_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Evening Primrose",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M01_Tsukimisou.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Everyday, Kachuusha",
    cover: "assets/covers/ebikachu.webp",
    audio: "assets/audio/lagu/everyday_kachuusha.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Faint",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/faint.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Fajar Sang Idola",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/fajar_sang_idola.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Fan Letter",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/fan_letter.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Finland Miracle",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/finland_miracle.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "First Rabbit",
    cover: "assets/covers/mahagita1.webp",
    audio: "assets/audio/lagu/first_rabbit.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Flying Get",
    cover: "assets/covers/flying_get.webp",
    audio: "assets/audio/lagu/flying_get.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Flying High",
    cover: "assets/covers/flying-high.webp",
    audio: "assets/audio/lagu/flying_high.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Fortune Cookie yang Mencinta",
    cover: "assets/covers/kfc.webp",
    audio: "assets/audio/lagu/fortune_cookie_yang_mencinta.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Freckles' Kiss",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/freckles_kiss.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Gadis Gadis Remaja",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/gadis_gadis_remaja.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Gadis Penjual Air Mata",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/lagu/gadis_penjual_air_mata.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Gadis Rambut Hitam yang punah",
    cover: "assets/covers/festival.webp",
    audio: "assets/audio/lagu/gadis_rambut_hitam_yang_punah.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Gadis Remaja",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/gadis_remaja.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "Medium",
  },
  {
    title: "Gadis SMA Putri Tidur",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/gadis_sma_putri_tidur.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Gadis Yang Celaka",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/gadis_yang_celaka.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "Nagiichi",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/gadis_yang_paling_cantik_di_pinggiran_pantai.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Ganteng Tapi Nanggung",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/ganteng_tapi_nanggung.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Garis Diagonal Cinta Searah",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/garis_diagonal_cinta_searah.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "Hizuke Henkousen",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/garis_pergantian_hari_cinta.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "Medium",
  },
  {
    title: "Gingham Check",
    cover: "assets/covers/ginghamcheck.webp",
    audio: "assets/audio/lagu/gingham_check.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Glory Days",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/glory_days.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "GO AND FIGHT!",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/go_and_fight.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Golden Center",
    cover: "assets/covers/bibirdrplastik.webp",
    audio: "assets/audio/lagu/golden_center.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Gonna Jump",
    cover: "assets/covers/believe.webp",
    audio: "assets/audio/lagu/gonna_jump.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Green Flash",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/green_flash.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "HA!",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/ha.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "HalLoween Night",
    cover: "assets/covers/halloween.webp",
    audio: "assets/audio/lagu/halloween_night.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "HalLoween Night (Dangdut Version)",
    cover: "assets/covers/halloween.webp",
    audio: "assets/audio/lagu/halloween_night_dangdut_version.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Hanya Lihat ke Depan",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/hanya_lihat_ke_depan.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Hanya Padamu Chu! Chu! Chu!",
    cover: "assets/covers/4gulali.webp",
    audio: "assets/audio/lagu/hanya_padamu_chu_chu_chu.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Harapan Bowling",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/harapan_bowling.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Sonichi",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/hari_pertama.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Heavy Rotation",
    cover: "assets/covers/heavyrotation.webp",
    audio: "assets/audio/lagu/heavy_rotation.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "High Tension",
    cover: "assets/covers/Hightension.webp",
    audio: "assets/audio/lagu/High_tension.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Honest Man",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/honest_man.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "How Come?",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/how_come.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Hubungan Kau Dan Aku",
    cover: "assets/covers/manatsu.webp",
    audio: "assets/audio/lagu/hubungan_kau_dan_aku.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Indahnya Senyum Manismu dst.",
    cover: "assets/covers/indahnyasenyum.webp",
    audio: "assets/audio/lagu/indahnya_senyum_manismu_dst.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Indera Keenam Seorang Gadis",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/indera_keenam_seorang_gadis.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Ingatan Kosmos",
    cover: "assets/covers/cosmos.webp",
    audio: "assets/audio/lagu/ingatan_kosmos.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Ingin Bertemu",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M03_Aitakatta.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Ingin Meraih Puncak!",
    cover: "assets/covers/halLoween.webp",
    audio: "assets/audio/lagu/ingin_meraih_puncak.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Innocence",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/innocence.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "J Stars",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/j_stars.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "Jadi Diri Sendiri",
    cover: "assets/covers/4gulali.webp",
    audio: "assets/audio/lagu/jadi_diri_sendiri.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Jadilah Batu yang Berputar",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/jadilah_batu_yang_berputar.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Terima Kasih",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/terima_kasih.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Jalan Melos",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M14_Jalan-Melos.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Jangan Panggil Diriku Idol",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/jangan_panggil_diriku_idol.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Janji Ya",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/janji_ya.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Jatuh Cinta Setiap Bertemu Denganmu",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/jatuh_cinta_setiap_bertemu_denganmu.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Jatuhkan dengan Kiss-Bye!",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M05_Jatuhkanlah-dgn-kiss-bye.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Jejak Awan Pesawat",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/jejak_awan_pesawat.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Jika Aku Dipelukmu",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/jika_aku_dipelukmu.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Jiwaru Days",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/jiwaru_days.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "JKT Datang!",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/jkt_datang.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "JKT Festival",
    cover: "assets/covers/festival.webp",
    audio: "assets/audio/lagu/jkt_festival.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "JKT48",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M12_Jakarta48.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Joan of Arc di Dalam Cermin",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/joan_of_arc_di_dalam_cermin.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Jurus Rahasia Teleport",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/jurus_rahasia_teleport.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Kaca Berbentuk I Love You",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M05_kaca_berbentuk_i-love-you.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Kakak Kelasku",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/kakak_kelasku.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Kaleidoscope",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/kaleidoscope.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Kalender yang Dipercepat",
    cover: "assets/covers/joy_kick_tears.webp",
    audio: "assets/audio/lagu/kalender_yang_dipercepat.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kali Ini Ecstasy",
    cover: "assets/covers/ginghamcheck.webp",
    audio: "assets/audio/lagu/kali_ini_ecstasy.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kamonegix",
    cover: "assets/covers/indahnyasenyum.webp",
    audio: "assets/audio/lagu/kamonegix.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kamulah yang Memberi Tahu Aku",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/kamulah_yang_memberi_tahu_aku.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Kapasitas Ikan Migrasi",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M12_Kapasitas_Ikan-Migrasi.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Karaage Cinta yang Tak Berbalas",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/karaage_cinta_yang_tak_berbalas.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Karena kau Ada Untukku",
    cover: "assets/covers/believe.webp",
    audio: "assets/audio/lagu/karena_kau_ada_untukku.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Karena Kusuka Dirimu",
    cover: "assets/covers/heavyrotation.webp",
    audio: "assets/audio/lagu/karena_kusuka_dirimu.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Kebenaran Tinju Ini",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/kebenaran_tinju_ini.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Keberadaan Cinta",
    cover: "assets/covers/keberadaan_cinta.webp",
    audio: "assets/audio/lagu/keberadaan_cinta.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Keberadaan Coklat Itu",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/keberadaan_coklat_itu.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Kebun Binatang Disaat Hujan",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/kebun_binatang_disaat_hujan.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Kebun Binatang Saat Hujan (New Era Version)",
    cover: "assets/covers/kebunnewera.webp",
    audio: "assets/audio/lagu/kebun_binatang_saat_hujan_new_era_version.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Kelopak-kelopak Bunga Sakura",
    cover: "assets/covers/ginghamcheck.webp",
    audio: "assets/audio/lagu/kelopakkelopak_bunga_sakura.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Kembang Api Milikku",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/kembang_api_milikku.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Kenyataan Yang Telah Ternoda",
    cover: "assets/covers/Hightension.webp",
    audio: "assets/audio/lagu/kenyataan_yang_telah_ternoda.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kereta Kedewasaan",
    cover: "assets/covers/joy_kick_tears.webp",
    audio: "assets/audio/lagu/kereta_kedewasaan.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Keringat itu Tidak Berbohong",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/keringat_itu_tidak_berbohong.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Kesepakatan Gencatan Senjata",
    cover: "assets/covers/beginner.webp",
    audio: "assets/audio/lagu/kesepakatan_gencatan_senjata.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kesucian Hati U-19",
    cover: "assets/covers/Hightension.webp",
    audio: "assets/audio/lagu/kesucian_hati_u19.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Keteguhan Hati Dandelion",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/keteguhan_hati_dandelion.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Khayalan",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M06_Khayalan.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Kilat yang Indah",
    cover: "assets/covers/ginghamcheck.webp",
    audio: "assets/audio/lagu/kilat_yang_indah.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kita Berdua Jadian",
    cover: "assets/covers/keberadaan_cinta.webp",
    audio: "assets/audio/lagu/kita_berdua_jadian.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Kita Pernah di Sini",
    cover: "assets/covers/melody.webp",
    audio: "assets/audio/lagu/kita_pernah_di_sini.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Kita tak Akan Biarkan Mimpi itu Mati",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/kita_tak_akan_biarkan_mimpi_itu_mati.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Kolam yang Tak Berair",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/kolam_yang_tak_berair.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Ku Tak Pantas Jadi Seorang Pujangga Cinta",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/ku_tak_pantas_jadi_seorang_pujangga_cinta.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Kucing Siam",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M15_Kucing_siam.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Kupu-kupu Yang Tak Dapat Terbang",
    cover: "assets/covers/teamj.webp",
    audio: "assets/audio/lagu/kupukupu_yang_tak_dapat_terbang.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Lagu 18 Bersaudari",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M09_18-Bersaudara.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Lagu Sahabat",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/lagu_sahabat.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Langit Biru Cinta Searah",
    cover: "assets/covers/k3_stage.webp",
    audio: "assets/audio/lagu/langit_biru_cinta_searah.mp3",
    type: "setlist",
    setlist: "kiii",
    popularity: "High",
  },
  {
    title: "Langit Biru Cinta Searah (Fly! Team T Version)",
    cover: "assets/covers/flyteamt.webp",
    audio: "assets/audio/lagu/langit_biru_cinta_searah_fly_team_t_version.mp3",
    type: "setlist",
    setlist: "flt",
    popularity: "High",
  },
  {
    title: "Langit Biru Cinta Searah (New Era Version)",
    cover: "assets/covers/langitbirucintasearah.webp",
    audio: "assets/audio/lagu/langit_biru_cinta_searah_new_era_version.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Lantang",
    cover: "assets/covers/jkt48acoustic.webp",
    audio: "assets/audio/lagu/lantang.mp3",
    type: "special",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Lap Time Masa Remaja",
    cover: "assets/covers/laptime.webp",
    audio: "assets/audio/lagu/lap_time_masa_remaja.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Larilah Penguin",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/larilah_penguin.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Lay down",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/lay_down.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "Medium",
  },
  {
    title: "Lebih dari Memori",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/lebih_dari_memori.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Locker Room Boy",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M09_Looker-room.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Love Chase",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/love_chase.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Love Trip",
    cover: "assets/covers/lovetrip.webp",
    audio: "assets/audio/lagu/love_trip.mp3",
    type: "single",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Luar Biasa",
    cover: "assets/covers/luarbiasa.webp",
    audio: "assets/audio/lagu/luar_biasa.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Lucky Seven",
    cover: "assets/covers/kokoro.webp",
    audio: "assets/audio/lagu/lucky_seven.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Lullaby Tanda Menyerah",
    cover: "assets/covers/3rd_Anniversary.webp",
    audio: "assets/audio/lagu/lullaby_tanda_menyerah.mp3",
    type: "special",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Maafkan, Hai Permataku",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M07_Maafkan_permataku.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "High",
  },
  {
    title: "Maafkan, Summer",
    cover: "assets/covers/heavyrotation.webp",
    audio: "assets/audio/lagu/maafkan_summer.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Magic Hour",
    cover: "assets/covers/magichour.webp",
    audio: "assets/audio/lagu/magic_hour.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Majisuka Rock n' Roll",
    cover: "assets/covers/joy_kick_tears.webp",
    audio: "assets/audio/lagu/majisuka_rock_n_roll.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Malaikat Hitam",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/malaikat_hitam.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Malam Hari Selasa, Pagi Hari Rabu",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/malam_hari_selasa_pagi_hari_rabu.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Malam Ulang Tahun",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M03_Malam_Ulang-Tahun.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Low",
  },
  {
    title: "Malu-malu Lollypop",
    cover: "assets/covers/flying_get.webp",
    audio: "assets/audio/lagu/malumalu_lollypop.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Mammoth",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M01_Mammoth.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "High",
  },
  {
    title: "Mango No.2",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/mango_no2.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Mari Menjadi Pohon Sakura",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/mari_menjadi_pohon_sakura.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "MARUKYUU 109",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/marukyuu_109_.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Masa Depan yang Menyilaukan Mata",
    cover: "assets/covers/masadepanmenyilaukan.webp",
    audio: "assets/audio/lagu/masa_depan_yang_menyilaukan_mata.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Matahari Milikku",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/matahari_milikku.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Mawar Natal Musim Panas",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/mawar_natal_musim_panas.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Melon Juice",
    cover: "assets/covers/luarbiasa.webp",
    audio: "assets/audio/lagu/melon_juice.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Membeku karena Selamat Tinggal",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/membeku_karena_selamat_tinggal.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Menanti",
    cover: "assets/covers/rapsodi.webp",
    audio: "assets/audio/lagu/menanti.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Menatapmu Sayonara",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/menatapmu_sayonara.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Mimpi yang Hina",
    cover: "assets/covers/rapsodi.webp",
    audio: "assets/audio/lagu/mimpi_yang_hina.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Mr. Kissman",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/mr_kissman.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Musim Panas Sounds Good!",
    cover: "assets/covers/manatsu.webp",
    audio: "assets/audio/lagu/musim_panas_sounds_good.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Musim Panas yang Kacau",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/musim_panas_yang_kacau.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Musim Panas Yang Kacau (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio: "assets/audio/lagu/musim_panas_yang_kacau_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Musim yang Selanjutnya",
    cover: "assets/covers/Hightension.webp",
    audio: "assets/audio/lagu/musim_yang_selanjutnya.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Must Be Now",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/must_be_now.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Namida no Shounan",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M02_Namida_no_Shounan.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Napas dalam Air Mata",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/napas_dalam_air_mata.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Natasha yang Ku Cinta",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/natasha_yang_ku_cinta.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "NEW SHIP",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/new_ship.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Nice to meet you!",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/nice_to_meet_you.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Oh my pumpkin!",
    cover: "assets/covers/pumkin.webp",
    audio: "assets/audio/lagu/oh_my_pumpkin.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Only Today",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/only_today.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "High",
  },
  {
    title: "Only Today (New Era Version)",
    cover: "assets/covers/newera.webp",
    audio: "assets/audio/lagu/only_today_new_era_version.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Onyx",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/onyx.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Overture",
    cover: "assets/default.jpg",
    audio: "assets/audio/lagu/overture.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Pada Malam yang Berbadai",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M06_Pada-Malam_berbadai.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Pajama Drive",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/pajama_drive.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Palu Keberanian",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M01_Palu_Keberanian.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Papan Tanda Isi Hati",
    cover: "assets/covers/kokoro.webp",
    audio: "assets/audio/lagu/papan_tanda_isi_hati.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Pareo adalah Emerald",
    cover: "assets/covers/pareo.webp",
    audio: "assets/audio/lagu/pareo_adalah_emerald.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Party Akan Dimulai",
    cover: "assets/covers/party.webp",
    audio: "assets/audio/lagu/party_akan_dimulai.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Party di Sudut Jalan",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/party_di_sudut_jalan.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Pasukan Pinokio",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/pasukan_pinokio.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Pelaut yang Melihat Mimpi di Tengah Badai",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/pelaut_yang_melihat_mimpi_di_tengah_badai.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Peluklah Aku Dari Belakang",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M07_Peluklah_Aku-Dari_Belakang.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Pembatas Buku Sakura",
    cover: "assets/covers/river.webp",
    audio: "assets/audio/lagu/pembatas_buku_sakura.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Pencuri Cinta Pertama",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/lagu/pencuri_cinta_pertama.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Penyangkalan Diri Requiem",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/penyangkalan_diri_requiem.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Perbuatan Angin Malam",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M09_Perbuatan_Angin-Malam.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Percik Kecil",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/percik_kecil.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Pergi Untuk Bertemu",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M13_Pergi_tuk-bertemu.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Persentase meteor",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M02_Persentase_Meteor.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Pertahanan akan Cinta",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/pertahanan_akan_cinta.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "Medium",
  },
  {
    title: "Pertanda",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/pertanda.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Pesawat Kertas 365 Hari",
    cover: "assets/covers/mahagita1.webp",
    audio: "assets/audio/lagu/pesawat_kertas_365_hari.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Pesawat Terbang Kertas Milik Kita",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/pesawat_terbang_kertas_milik_kita.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Petak Umpet Romansa",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/petak_umpet_romansa.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Pin Heel Merah dan Profesor",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/pin_heel_merah_dan_profesor.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Pintu Masa Depan",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M11_Pintu_Masa_Depan.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Pioneer",
    cover: "assets/covers/lovetrip.webp",
    audio: "assets/audio/lagu/pioneer.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Ponytail dan Shu-shu",
    cover: "assets/covers/ponytail.webp",
    audio: "assets/audio/lagu/ponytail_dan_shushu.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Prinsip Kesucian Hati",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/prinsip_kesucian_hati.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Pulang Kampung",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/pulang_kampung.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Migikata",
    cover: "assets/covers/bukanalpukat.webp",
    audio: "assets/audio/lagu/pundak_kanan.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Punggung milikmu",
    cover: "assets/covers/beginner.webp",
    audio: "assets/audio/lagu/punggung_milikmu.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Punkish",
    cover: "assets/covers/pumkin.webp",
    audio: "assets/audio/lagu/punkish.mp3",
    type: "special",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Pura-Pura dan Kepalsuan",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/purapura_dan_kepalsuan.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Benang Sari, Putik, dan Kupu-Kupu Malam",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M08_Oshibe.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "High",
  },
  {
    title: "Putri Duyung yang Sedang Sedih",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/putri_duyung_yang_sedang_sedih.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Raja Hati",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/raja_hati.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Rapsodi",
    cover: "assets/covers/rapsodi.webp",
    audio: "assets/audio/lagu/rapsodi.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Keibetsu Shiteita Aijou",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/rasa_sayang_yang_dulu_kuremehkan.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Rasanya Capek",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/rasanya_capek.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Low",
  },
  {
    title: "Ratu Para Idola",
    cover: "assets/covers/halLoween.webp",
    audio: "assets/audio/lagu/ratu_para_idola.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Refrain Penuh Harapan",
    cover: "assets/covers/kibouteki.webp",
    audio: "assets/audio/lagu/refrain_penuh_harapan.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Relax!",
    cover: "assets/covers/bukanalpukat.webp",
    audio: "assets/audio/lagu/relax.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Rencana Cinta",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M06_Rencana_Cinta.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Return Match",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M05_Return_Match.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Revolusi Rio",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M08_Revolusi_Rio.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Rider",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M07_Rider.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "RIVER",
    cover: "assets/covers/river.webp",
    audio: "assets/audio/lagu/river.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Rok Bergoyang",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M12_Rok_Bergoyang.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Romance Rocket",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/romance_rocket.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Romantic Snow",
    cover: "assets/covers/romasnow.webp",
    audio: "assets/audio/lagu/romantic_snow.mp3",
    type: "special",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Rugi Sudah Dicium",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/rugi_sudah_dicium.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "RUN RUN RUN",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/run_run_run.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Saatnya Kesempatan",
    cover: "assets/covers/kesempatan.webp",
    audio: "assets/audio/lagu/saatnya_kesempatan.mp3",
    type: "special",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Sahabat atau Cinta",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/sahabat_atau_cinta.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Sakura Kita Makan Bersama",
    cover: "assets/covers/luarbiasa.webp",
    audio: "assets/audio/lagu/sakura_kita_makan_bersama.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Salah Dengar Rock",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/salah_dengar_rock.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Sambil Menggandeng Erat Tangnku",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/sambil_menggandeng_erat_tangnku.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Sampai Dirimu Menjadi Bintang",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/sampai_dirimu_menjadi_bintang.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Sampai Jumpa Lagi",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/sampai_jumpa_lagi.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
  {
    title: "Sampai Musim Semi Tiba",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/sampai_musim_semi_tiba.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "Medium",
  },
  {
    title: "Sang Hujan yang Kejam",
    cover: "assets/covers/pasion.webp",
    audio: "assets/audio/lagu/sang_hujan_yang_kejam.mp3",
    type: "setlist",
    setlist: "pasion",
    popularity: "Medium",
  },
  {
    title: "Sang Pianis Hujan",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/sang_pianis_hujan.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Sayonara Crawl",
    cover: "assets/covers/sayonara_crawl.webp",
    audio: "assets/audio/lagu/sayonara_crawl.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Schoolyard Puppy",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/schoolyard_puppy.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Scrap and Build",
    cover: "assets/covers/luarbiasa.webp",
    audio: "assets/audio/lagu/scrap_and_build.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Sebagian besar kenangan",
    cover: "assets/covers/melody.webp",
    audio: "assets/audio/lagu/sebagian_besar_kenangan.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Seberangi Lautan",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/seberangi_lautan.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Low",
  },
  {
    title: "Sedikit Saja I Love You",
    cover: "assets/covers/indahnyasenyum.webp",
    audio: "assets/audio/lagu/sedikit_saja_i_love_you.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Seesaw Game Penuh Air Mata",
    cover: "assets/covers/ebikachu.webp",
    audio: "assets/audio/lagu/seesaw_game_penuh_air_mata.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Sekarang Ku Bersama Denganmu",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/sekarang_ku_bersama_denganmu.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Sekarang Para-Para",
    cover: "assets/covers/ebikachu.webp",
    audio: "assets/audio/lagu/sekarang_parapara.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "sekarang sedang jatuh cinta",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/lagu/sekarang_sedang_jatuh_cinta.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "High",
  },
  {
    title: "Selamanya Pressure",
    cover: "assets/covers/kaze.webp",
    audio: "assets/audio/lagu/selamanya_pressure.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Seragam Ini Sangat Mengganggu",
    cover: "assets/covers/tadaima.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M08_Seragam_sangat-mengganggu.mp3",
    type: "setlist",
    setlist: "Tadaima Renaichu",
    popularity: "High",
  },
  {
    title: "Serigala dan Pride",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/serigala_dan_pride.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Setlist yang Dinanti",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/setlist_yang_dinanti.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Seventeen",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/seventeen.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Si Bintang Jatuh Yang Egois",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/si_bintang_jatuh_yang_egois.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "Medium",
  },
  {
    title: "Si Ulat Penakut",
    cover: "assets/covers/romasnow.webp",
    audio: "assets/audio/lagu/si_ulat_penakut.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Siapa yang Membuat Kita Berdua Bertemu?",
    cover: "assets/covers/rapsodi.webp",
    audio: "assets/audio/lagu/siapa_yang_membuat_kita_berdua_bertemu.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Simpati Gravitasi",
    cover: "assets/covers/kaze.webp",
    audio: "assets/audio/lagu/simpati_gravitasi.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Sneakers Waktu Itu",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/sneakers_waktu_itu.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High", 
  },
  {
    title: "So Long!",
    cover: "assets/covers/solong.webp",
    audio: "assets/audio/lagu/so_long.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Stand up",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M10_Stand-Up.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Low",
  },
  {
    title: "Stasiun Daun Kering",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/stasiun_daun_kering.mp3",
    type: "setlist",
    setlist: "tunas dibalik seragam",
    popularity: "High",
  },
  {
    title: "Stripper Cinta",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/setlist/Dewi_Theater/M03_Stripper-Cinta.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Sugar Rush",
    cover: "assets/covers/sugarrush.webp",
    audio: "assets/audio/lagu/sugar_rush.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Suka Suka Suka",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/suka_suka_suka.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Suka! Suka! Skip!",
    cover: "assets/covers/beginner.webp",
    audio: "assets/audio/lagu/suka_suka_skip.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Summer Has Gone",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M09_Summer-has-gone.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Sungai Impian",
    cover: "assets/covers/luarbiasa.webp",
    audio: "assets/audio/lagu/sungai_impian.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Surat Undangan Sang Angin Laut",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/surat_undangan_sang_angin_laut.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "High",
  },
  {
    title: "Sweet & Bitter",
    cover: "assets/covers/rapsodi.webp",
    audio: "assets/audio/lagu/sweet_bitter.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Switch",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/switch.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Tak Bisa Berhenti jadi Gadis SMA",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/tak_bisa_berhenti_jadi_gadis_sma.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "Medium",
  },
  {
    title: "Tak Ingin Jadi Orang Hebat",
    cover: "assets/covers/belterakhir.webp",
    audio: "assets/audio/setlist/Bel_terakhir/M04_Tidak_ingin_menjadi_oranghebat.mp3",
    type: "setlist",
    setlist: "Bell Terakhir Berbunyi",
    popularity: "Medium",
  },
  {
    title: "Tali Persahabatan",
    cover: "assets/covers/twt.webp",
    audio: "assets/audio/lagu/tali_persahabatan.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Tangga Surga",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/tangga_surga.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Teacher Teacher",
    cover: "assets/covers/banzai.webp",
    audio: "assets/audio/lagu/teacher_teacher.mp3",
    type: "setlist",
    setlist: "Banzai",
    popularity: "High",
  },
  {
    title: "Team J Oshi",
    cover: "assets/covers/dewi.webp",
    audio: "assets/audio/lagu/team_j_oshi.mp3",
    type: "setlist",
    setlist: "dewi theater",
    popularity: "Medium",
  },
  {
    title: "Telapak Tangan",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/telapak_tangan.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "High",
  },
  {
    title: "Tentang Suratku",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/tentang_suratku.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Terhina",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/terhina.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "High",
  },
  {
    title: "Teriakan Berlian",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/teriakan_berlian.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Terima Kasih",
    cover: "assets/covers/fajar.webp",
    audio: "assets/audio/lagu/terima_kasih.mp3",
    type: "setlist",
    setlist: "fajar sang idola",
    popularity: "High",
  },
  {
    title: "Tersenyum Sambil Menangis",
    cover: "assets/covers/rh2016.webp",
    audio: "assets/audio/lagu/tersenyum_sambil_menangis.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Tetapi...",
    cover: "assets/covers/aitakatta.webp",
    audio: "assets/audio/setlist/Aitakatta/M09_Tetapi.mp3",
    type: "setlist",
    setlist: "Ingin Bertemu",
    popularity: "High",
  },
  {
    title: "Tetaplah Ada di Langit Biru",
    cover: "assets/covers/lovetrip.webp",
    audio: "assets/audio/lagu/tetaplah_ada_di_langit_biru.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Tidak Boleh Pelukan",
    cover: "assets/covers/liatkedepan.webp",
    audio: "assets/audio/lagu/tidak_boleh_pelukan.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "To Be Continued",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/to_be_continued.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "High",
  },
  {
    title: "Tolong Ingatlah",
    cover: "assets/covers/mahagita2.webp",
    audio: "assets/audio/lagu/tolong_ingatlah.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Tsundere!",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/tsundere.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Tunas di Balik Seragam",
    cover: "assets/covers/tunas.webp",
    audio: "assets/audio/lagu/tunas_di_balik_seragam.mp3",
    type: "setlist",
    setlist: "Te wo Tsunaginagara",
    popularity: "High",
  },
  {
    title: "Two Years Later",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/two_years_later.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "UZA",
    cover: "assets/covers/uza.webp",
    audio: "assets/audio/lagu/uza.mp3",
    type: "single",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Valentine Day Kiss",
    cover: "assets/covers/4gulali.webp",
    audio: "assets/audio/lagu/valentine_day_kiss.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Value Milikku Saja",
    cover: "assets/covers/kibouteki.webp",
    audio: "assets/audio/lagu/value_milikku_saja.mp3",
    type: "album",
    setlist: null,
    popularity: "High",
  },
  {
    title: "Virgin Love",
    cover: "assets/covers/sg.webp",
    audio: "assets/audio/lagu/virgin_love.mp3",
    type: "setlist",
    setlist: "seishun girls",
    popularity: "High",
  },
  {
    title: "Virginity",
    cover: "assets/covers/solong.webp",
    audio: "assets/audio/lagu/virginity.mp3",
    type: "album",
    setlist: null,
    popularity: "Low",
  },
  {
    title: "Virus Tipe Hati",
    cover: "assets/covers/rkj.webp",
    audio: "assets/audio/lagu/virus_tipe_hati.mp3",
    type: "setlist",
    setlist: "aturan anti cinta",
    popularity: "High",
  },
  {
    title: "Viva! Hurricane!",
    cover: "assets/covers/matahari.webp",
    audio: "assets/audio/lagu/viva_hurricane.mp3",
    type: "setlist",
    setlist: "matahari milikku",
    popularity: "High",
  },
  {
    title: "Wahai Kesatria",
    cover: "assets/covers/ebikachu.webp",
    audio: "assets/audio/lagu/wahai_kesatria.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Waiting Room",
    cover: "assets/covers/believe.webp",
    audio: "assets/audio/lagu/waiting_room.mp3",
    type: "album",
    setlist: null,
    popularity: "Medium",
  },
  {
    title: "Warna Cinta",
    cover: "assets/covers/sakaagari.webp",
    audio: "assets/audio/lagu/warna_cinta.mp3",
    type: "setlist",
    setlist: "saka agari",
    popularity: "High",
  },
  {
    title: "Warning",
    cover: "assets/covers/dnt.webp",
    audio: "assets/audio/setlist/Demi_Seseorang/M02_Warning.mp3",
    type: "setlist",
    setlist: "Demi Seseorang",
    popularity: "Medium",
  },
  {
    title: "Wasshoi J!",
    cover: "assets/covers/pajama.webp",
    audio: "assets/audio/lagu/wasshoi_j.mp3",
    type: "setlist",
    setlist: "Pajama Drive",
    popularity: "High",
  },
  {
    title: "Winning Ball",
    cover: "assets/covers/Ramune.webp",
    audio: "assets/audio/lagu/winning_ball.mp3",
    type: "setlist",
    setlist: "Cara Meminum Ramune",
    popularity: "High",
  },
  {
    title: "Wish You",
    cover: "assets/covers/percin.webp",
    audio: "assets/audio/lagu/wish_you.mp3",
    type: "setlist",
    setlist: "pertaruhan cinta",
    popularity: "High",
  },
]
